### ISSUE TITLE
Usable with windows?

### ISSUE THREAD

**Issue by Charwisc-py** [Euronymou5/Doxxer-Toolkit#2]
You can not currently run the requirement installer in windows.

**Comment by Darkrevengehack** [comment]
> Actualmente no puede ejecutar el instalador de requisitos en Windows.

Bro, tienes que ejecutar el instalador de requisitos para windows en la terminal de windows.

Nota: Si no tienes la terminal de windows 10 en tu windows, entonces descargala oficialmente desde microsoft: https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=es-ar&gl=ar

**Comment by Darkrevengehack** [comment]
> > Actualmente no puede ejecutar el instalador de requisitos en Windows.
> 
> Bro, tienes que ejecutar el instalador de requisitos para windows en la terminal de windows.
> 
> Nota: Si no tienes la terminal de windows 10 en tu windows, entonces descargala oficialmente desde microsoft: https://apps.microsoft.com/store/detail/windows-terminal/9N0DX20HK701?hl=es-ar&gl=ar

Nota: Si se te solucionó el problema, cierra la apertura de este problema.

**Comment by Euronymou5** [comment]
> You can not currently run the requirement installer in windows.


doxxer toolkit is only compatible with linux.
