### ISSUE TITLE
Error when starting the tool

### ISSUE THREAD

**Issue by spacemles** [Euronymou5/Doxxer-Toolkit#30]
![imagen_2024-12-20_164853835](https://github.com/user-attachments/assets/6e78aa8d-27c9-426c-8c9b-83ce7c15f6e1)
What happens is that when I try to open the tool I get the 'pyshorteners' error and yes... I already have python 3 installed and Kali Linux updated to this date

**Comment by Euronymou5** [comment]
> ![imagen_2024-12-20_164853835](https://private-user-images.githubusercontent.com/180860679/397791016-6e78aa8d-27c9-426c-8c9b-83ce7c15f6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3MjY3MjMsIm5iZiI6MTczNDcyNjQyMywicGF0aCI6Ii8xODA4NjA2NzkvMzk3NzkxMDE2LTZlNzhhYThkLTI3YzktNDI2Yy04YzliLTgzY2U3YzE1ZjZlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQyMDI3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTVhNTZmY2YwNThjMjc2ODUyZTYzNzY4ZmJkZDEyNTVjMTYwNThhZmFlNmFlYTJjNjg5MTRmYzJmODk4MDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P2PLDiXOVhgLZKHlPn34saV24yGNcSaFv5yyrAfyYJY) What happens is that when I try to open the tool I get the 'pyshorteners' error and yes... I already have python 3 installed and Kali Linux updated to this date

You have to install the requirements, preferably: **pip3 install -r requirements.txt**

**Comment by spacemles** [comment]
![imagen_2024-12-21_005145593](https://github.com/user-attachments/assets/f3c0b16d-3803-444f-9413-bf02119bac76)
later bro?

**Comment by Euronymou5** [comment]
> later bro?

This error became very common with the latest versions of Python, try: **pip3 install -r requirements.txt --break-system-packages**

**Comment by spacemles** [comment]
It has worked for me, thank you very much :)
