### ISSUE TITLE
"ModuleNotFoundError: No module named 'pyshorteners'

### ISSUE THREAD

**Issue by DN1010** [Euronymou5/Doxxer-Toolkit#7]
estoy usando archlinux y no puedo correr la aplicacion

**Comment by Euronymou5** [comment]
> estoy usando archlinux y no puedo correr la aplicacion

Prueba con:

pip3 install pyshorteners

o

pip3 install pyshorteners --break-system-packages

**Comment by DN1010** [comment]
Una ultima pregunta habra forma de editar el programa para quitar lo raro es que lo quiero usar para una demostracion de prevencion del cyber acoso una

**Comment by DN1010** [comment]
BTW parece que solo tenia que importar de las lineas 10, 13 y 14

**Comment by Euronymou5** [comment]
> Una ultima pregunta habra forma de editar el programa para quitar lo raro es que lo quiero usar para una demostracion de prevencion del cyber acoso una

El codigo es open source, se puede editar cuando quieras

**Comment by vixho69** [comment]
:v
