### ISSUE TITLE
Oye el pip no es necesario desinstalarlo e instalarlo de nuevo, está mal eso, porque ya viene termux con un pip actualizado y sin nada raro.

### ISSUE THREAD

**Issue by Darkrevengehack** [Euronymou5/Doxxer-Toolkit#8]
Quitar ese defecto.

**Comment by Euronymou5** [comment]
Lo agregué porque, en las versiones de Kali Linux de aproximadamente 2021 (Cuando se creo Doxxer-Toolkit), ocurría un error al hacer "apt install python3-pip". Igualmente, en Termux, pero como dices que ya viene en Termux, quizás deba quitarlo.

**Comment by Darkrevengehack** [comment]
> Lo agregué porque, en las versiones de Kali Linux de aproximadamente 2021 (Cuando se creo Doxxer-Toolkit), ocurría un error al hacer "apt install python3-pip". Igualmente, en Termux, pero como dices que ya viene en Termux, quizás deba quitarlo.

Si, pero tendrías que agregar la excepción en termux, ya que el hecho de que hagas eso con pip en Kali Linux es una cosa, pero en termux es otra, puedes hacerlo? Pls, nos harías un favor a todos.

**Comment by Euronymou5** [comment]
> > Lo agregué porque, en las versiones de Kali Linux de aproximadamente 2021 (Cuando se creo Doxxer-Toolkit), ocurría un error al hacer "apt install python3-pip". Igualmente, en Termux, pero como dices que ya viene en Termux, quizás deba quitarlo.
> 
> Si, pero tendrías que agregar la excepción en termux, ya que el hecho de que hagas eso con pip en Kali Linux es una cosa, pero en termux es otra, puedes hacerlo? Pls, nos harías un favor a todos.

Agregaré que detecte automáticamente si pip3 se encuentra instalado y, si está instalado, simplemente salte esa parte de la instalación. Si no lo está, entonces que se instale automáticamente.
