### ISSUE TITLE
ModuleNotFoundError: No module named 'pyshorteners'

### ISSUE THREAD

**Issue by bumbembam** [Euronymou5/Doxxer-Toolkit#9]
I use Termux with Android and the following error comes up:ModuleNotFoundError: No module named 'pyshorteners' please help me figure this out.

**Comment by Merghany098** [comment]
Pip install pyshorteners

**Comment by nn4453** [comment]
same problem on ubuntu

**Comment by Euronymou5** [comment]
they need to manually install the dependencies with: `pip3 install -r requirements.txt`. If it still doesn't let them, they probably need to upgrade their system
